### ISSUE TITLE
Problem with pdf version >=1.4

### ISSUE THREAD

**Issue by pippuccio76** [libremente/PDFMerger#2]
Hi , sorry fo english , when i try to merge file with 1.4 version i have an exception :

Unknown HTTP status code provided with no message: 267

**Comment by libremente** [comment]
Dear @pippuccio76, unfortunately I cannot help you with this issue since I'm not working on this project anymore, I will add a notice in the README. I've seen that you opened the same issue in other repos so I hope someone else will be able to help you on this. Good luck!
